#!/usr/bin/env bash
# Generate strong secrets, write .env, and bring the Langfuse stack up.
#
# Usage:
#   ./setup.sh                      # interactive — prompts for the public URL
#   ./setup.sh https://lf.example.com  # non-interactive
#
# Re-running is safe. If .env already exists, the script refuses to overwrite
# unless you pass --force.

set -euo pipefail

cd "$(dirname "$0")"

FORCE=0
PUBLIC_URL=""

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    https://*|http://*) PUBLIC_URL="$arg" ;;
    -h|--help)
      grep -E '^# ' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -f .env && $FORCE -ne 1 ]]; then
  echo ".env already exists — pass --force to overwrite, or edit it manually" >&2
  exit 1
fi

if [[ -z "$PUBLIC_URL" ]]; then
  read -rp "Public URL Langfuse will be served at (e.g. https://lf.example.com): " PUBLIC_URL
fi
if [[ ! "$PUBLIC_URL" =~ ^https?:// ]]; then
  echo "PUBLIC_URL must start with http:// or https://" >&2
  exit 2
fi

# A few helpers — fallback chain across python3 / openssl in case the host
# is missing one.
gen_token() {
  local n="${1:-32}"
  if command -v python3 >/dev/null; then
    python3 -c "import secrets,sys; print(secrets.token_urlsafe(int(sys.argv[1])))" "$n"
  else
    openssl rand -base64 "$n" | tr -d '\n=+/' | head -c "$((n*4/3))"
  fi
}
gen_hex() {
  if command -v python3 >/dev/null; then
    python3 -c "import os; print(os.urandom(32).hex())"
  else
    openssl rand -hex 32
  fi
}
gen_lf_key() {
  local prefix="$1"
  if command -v python3 >/dev/null; then
    python3 -c "import secrets,string,sys; print(sys.argv[1]+''.join(secrets.choice(string.ascii_letters+string.digits) for _ in range(36)))" "$prefix"
  else
    echo "${prefix}$(openssl rand -hex 18)"
  fi
}

NEXTAUTH_SECRET=$(gen_token 48)
SALT=$(gen_token 48)
ENCRYPTION_KEY=$(gen_hex)
POSTGRES_PASSWORD=$(gen_token 32)
CLICKHOUSE_PASSWORD=$(gen_token 32)
REDIS_AUTH=$(gen_token 32)
MINIO_ROOT_PASSWORD=$(gen_token 32)
INIT_PK=$(gen_lf_key "pk-lf-")
INIT_SK=$(gen_lf_key "sk-lf-")
INIT_PW=$(gen_token 18)

cat > .env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT.

NEXTAUTH_URL=${PUBLIC_URL}
LANGFUSE_WEB_PORT=3000

NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
SALT=${SALT}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
REDIS_AUTH=${REDIS_AUTH}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

AUTH_DISABLE_SIGNUP=true
TELEMETRY_ENABLED=false

LANGFUSE_INIT_ORG_ID=default
LANGFUSE_INIT_ORG_NAME=Default
LANGFUSE_INIT_PROJECT_ID=default
LANGFUSE_INIT_PROJECT_NAME=default
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${INIT_PK}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${INIT_SK}
LANGFUSE_INIT_USER_EMAIL=admin@example.com
LANGFUSE_INIT_USER_NAME=Admin
LANGFUSE_INIT_USER_PASSWORD=${INIT_PW}
EOF

chmod 600 .env
echo "wrote .env (chmod 600)"

DOCKER=docker
if ! docker compose version >/dev/null 2>&1; then
  DOCKER="sudo docker"
fi

echo "pulling images..."
$DOCKER compose pull
echo "starting stack..."
$DOCKER compose up -d

echo ""
echo "==============================="
echo "Langfuse is starting."
echo ""
echo "  Web UI:        ${PUBLIC_URL}"
echo "  Admin email:   admin@example.com"
echo "  Admin pass:    ${INIT_PW}"
echo ""
echo "  Public key:    ${INIT_PK}"
echo "  Secret key:    ${INIT_SK}"
echo ""
echo "All secrets are in .env (do not commit)."
echo "Wait ~30s for migrations, then check:"
echo "  curl -fsS http://127.0.0.1:3000/api/public/health"
echo "==============================="
